export const PROJECTS = [
  {
    id: 1,
    nama: "POS App",
    gambar: "web9.png",
    bahasa: "Electron.js, React.js, TailwindCSS",
    github: "#",
    link: "https://localhost:5173/",
  },
  {
    id: 2,
    nama: "Blog App",
    gambar: "web8.png",
    bahasa: "MongoDB, Express.js, React.js, Node JS, TailwindCSS",
    github: "https://github.com/jordi15101999/MERN-BlogApp",
    link: "https://localhost:5173/",
  },
  {
    id: 3,
    nama: "Football Top Leagues Standings",
    gambar: "web1.png",
    bahasa: "React.js, Bootstrap, Vite ",
    github: "https://github.com/jordi15101999/standingtables",
    link: "https://standings-topleagues.netlify.app/",
  },
  {
    id: 4,
    nama: "Cashier App",
    gambar: "web3.png",
    bahasa: "React.js, Json, Bootstrap, SweetAlert",
    github: "#",
    link: "https://jj-cashier.netlify.app/",
  },
  {
    id: 5,
    nama: "ChatApp with Firebase",
    gambar: "web4.png",
    bahasa: "React.js, Firebase, TailwindCSS",
    github: "#",
    link: "https://jj-chat.netlify.app/",
  },
  {
    id: 6,
    nama: "Attendance App ( Final Project )",
    gambar: "web5.png",
    bahasa: "CodeIgniter, JavaScript, Bootstrap, MySql ",
    github: "#",
    link: "#",
  },
  {
    id: 7,
    nama: "Personal Portfolio",
    gambar: "web6.png",
    bahasa: "React.js, TailwindCSS, Vite",
    github: "https://github.com/jordi15101999/react-portfolio",
    link: "https://portfolio-johjordi.netlify.app/",
  },
  {
    id: 8,
    nama: "Company Profile",
    gambar: "web7.png",
    bahasa: "HTML, MaterializeCSS, JavaScript",
    github: "https://github.com/jordi15101999/comprofile",
    link: "https://jj-comprofile.netlify.app/",
  },
];
